// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Address Book

    Schemes:
      http
    Host: localhost:8765
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
