// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/powerman/go-service-example/api/openapi/model"
)

// NewAddContactParams creates a new AddContactParams object
// with the default values initialized.
func NewAddContactParams() *AddContactParams {
	var ()
	return &AddContactParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddContactParamsWithTimeout creates a new AddContactParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddContactParamsWithTimeout(timeout time.Duration) *AddContactParams {
	var ()
	return &AddContactParams{

		timeout: timeout,
	}
}

// NewAddContactParamsWithContext creates a new AddContactParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddContactParamsWithContext(ctx context.Context) *AddContactParams {
	var ()
	return &AddContactParams{

		Context: ctx,
	}
}

// NewAddContactParamsWithHTTPClient creates a new AddContactParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddContactParamsWithHTTPClient(client *http.Client) *AddContactParams {
	var ()
	return &AddContactParams{
		HTTPClient: client,
	}
}

/*AddContactParams contains all the parameters to send to the API endpoint
for the add contact operation typically these are written to a http.Request
*/
type AddContactParams struct {

	/*Args*/
	Args *model.Contact

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add contact params
func (o *AddContactParams) WithTimeout(timeout time.Duration) *AddContactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add contact params
func (o *AddContactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add contact params
func (o *AddContactParams) WithContext(ctx context.Context) *AddContactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add contact params
func (o *AddContactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add contact params
func (o *AddContactParams) WithHTTPClient(client *http.Client) *AddContactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add contact params
func (o *AddContactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the add contact params
func (o *AddContactParams) WithArgs(args *model.Contact) *AddContactParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the add contact params
func (o *AddContactParams) SetArgs(args *model.Contact) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *AddContactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Args != nil {
		if err := r.SetBodyParam(o.Args); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
