// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListContactsParams creates a new ListContactsParams object
// with the default values initialized.
func NewListContactsParams() *ListContactsParams {
	var ()
	return &ListContactsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListContactsParamsWithTimeout creates a new ListContactsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListContactsParamsWithTimeout(timeout time.Duration) *ListContactsParams {
	var ()
	return &ListContactsParams{

		timeout: timeout,
	}
}

// NewListContactsParamsWithContext creates a new ListContactsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListContactsParamsWithContext(ctx context.Context) *ListContactsParams {
	var ()
	return &ListContactsParams{

		Context: ctx,
	}
}

// NewListContactsParamsWithHTTPClient creates a new ListContactsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListContactsParamsWithHTTPClient(client *http.Client) *ListContactsParams {
	var ()
	return &ListContactsParams{
		HTTPClient: client,
	}
}

/*ListContactsParams contains all the parameters to send to the API endpoint
for the list contacts operation typically these are written to a http.Request
*/
type ListContactsParams struct {

	/*Args*/
	Args ListContactsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list contacts params
func (o *ListContactsParams) WithTimeout(timeout time.Duration) *ListContactsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list contacts params
func (o *ListContactsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list contacts params
func (o *ListContactsParams) WithContext(ctx context.Context) *ListContactsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list contacts params
func (o *ListContactsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list contacts params
func (o *ListContactsParams) WithHTTPClient(client *http.Client) *ListContactsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list contacts params
func (o *ListContactsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the list contacts params
func (o *ListContactsParams) WithArgs(args ListContactsBody) *ListContactsParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the list contacts params
func (o *ListContactsParams) SetArgs(args ListContactsBody) {
	o.Args = args
}

// WriteToRequest writes these params to a swagger request
func (o *ListContactsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Args); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
