// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/powerman/go-service-example/api/openapi/model"
)

// ListContactsReader is a Reader for the ListContacts structure.
type ListContactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListContactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListContactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListContactsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListContactsOK creates a ListContactsOK with default headers values
func NewListContactsOK() *ListContactsOK {
	return &ListContactsOK{}
}

/*ListContactsOK handles this case with default header values.

OK
*/
type ListContactsOK struct {
	Payload []*model.Contact
}

func (o *ListContactsOK) Error() string {
	return fmt.Sprintf("[GET /contacts][%d] listContactsOK  %+v", 200, o.Payload)
}

func (o *ListContactsOK) GetPayload() []*model.Contact {
	return o.Payload
}

func (o *ListContactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListContactsDefault creates a ListContactsDefault with default headers values
func NewListContactsDefault(code int) *ListContactsDefault {
	return &ListContactsDefault{
		_statusCode: code,
	}
}

/*ListContactsDefault handles this case with default header values.

Generic error response.
*/
type ListContactsDefault struct {
	_statusCode int

	Payload *model.Error
}

// Code gets the status code for the list contacts default response
func (o *ListContactsDefault) Code() int {
	return o._statusCode
}

func (o *ListContactsDefault) Error() string {
	return fmt.Sprintf("[GET /contacts][%d] listContacts default  %+v", o._statusCode, o.Payload)
}

func (o *ListContactsDefault) GetPayload() *model.Error {
	return o.Payload
}

func (o *ListContactsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
