// Package migrations provides goose migrations.
package migrations

import (
	"github.com/powerman/go-service-example/pkg/def"
	goosepkg "github.com/powerman/goose/v2"
)

//nolint:gochecknoglobals // Force code generated by `goose create` to use instance.
var goose = def.NewGoose()

// Goose returns goose instance with Go migrations defined in the package.
func Goose() *goosepkg.Instance { return goose }
