// Code generated by MockGen. DO NOT EDIT.
// Source: app.go

// Package app is a generated GoMock package.
package app

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAppl is a mock of Appl interface
type MockAppl struct {
	ctrl     *gomock.Controller
	recorder *MockApplMockRecorder
}

// MockApplMockRecorder is the mock recorder for MockAppl
type MockApplMockRecorder struct {
	mock *MockAppl
}

// NewMockAppl creates a new mock instance
func NewMockAppl(ctrl *gomock.Controller) *MockAppl {
	mock := &MockAppl{ctrl: ctrl}
	mock.recorder = &MockApplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAppl) EXPECT() *MockApplMockRecorder {
	return m.recorder
}

// Contacts mocks base method
func (m *MockAppl) Contacts(arg0 Ctx, arg1 Auth) ([]Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Contacts", arg0, arg1)
	ret0, _ := ret[0].([]Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Contacts indicates an expected call of Contacts
func (mr *MockApplMockRecorder) Contacts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contacts", reflect.TypeOf((*MockAppl)(nil).Contacts), arg0, arg1)
}

// AddContact mocks base method
func (m *MockAppl) AddContact(arg0 Ctx, arg1 Auth, name string) (*Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContact", arg0, arg1, name)
	ret0, _ := ret[0].(*Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddContact indicates an expected call of AddContact
func (mr *MockApplMockRecorder) AddContact(arg0, arg1, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContact", reflect.TypeOf((*MockAppl)(nil).AddContact), arg0, arg1, name)
}

// MockRepo is a mock of Repo interface
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// Contacts mocks base method
func (m *MockRepo) Contacts(arg0 Ctx) ([]Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Contacts", arg0)
	ret0, _ := ret[0].([]Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Contacts indicates an expected call of Contacts
func (mr *MockRepoMockRecorder) Contacts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contacts", reflect.TypeOf((*MockRepo)(nil).Contacts), arg0)
}

// AddContact mocks base method
func (m *MockRepo) AddContact(arg0 Ctx, arg1 *Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContact", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContact indicates an expected call of AddContact
func (mr *MockRepoMockRecorder) AddContact(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContact", reflect.TypeOf((*MockRepo)(nil).AddContact), arg0, arg1)
}
