// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	model "github.com/powerman/go-service-goswagger-clean-example/internal/api/model"
)

// GetContactsOKCode is the HTTP code returned for type GetContactsOK
const GetContactsOKCode int = 200

/*GetContactsOK Contacts list

swagger:response getContactsOK
*/
type GetContactsOK struct {

	/*
	  In: Body
	*/
	Payload []*model.Contact `json:"body,omitempty"`
}

// NewGetContactsOK creates GetContactsOK with default headers values
func NewGetContactsOK() *GetContactsOK {

	return &GetContactsOK{}
}

// WithPayload adds the payload to the get contacts o k response
func (o *GetContactsOK) WithPayload(payload []*model.Contact) *GetContactsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get contacts o k response
func (o *GetContactsOK) SetPayload(payload []*model.Contact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContactsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*model.Contact, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *GetContactsOK) GetContactsResponder() {}

/*GetContactsDefault Error

swagger:response getContactsDefault
*/
type GetContactsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewGetContactsDefault creates GetContactsDefault with default headers values
func NewGetContactsDefault(code int) *GetContactsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetContactsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get contacts default response
func (o *GetContactsDefault) WithStatusCode(code int) *GetContactsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get contacts default response
func (o *GetContactsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get contacts default response
func (o *GetContactsDefault) WithPayload(payload *model.Error) *GetContactsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get contacts default response
func (o *GetContactsDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContactsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetContactsDefault) GetContactsResponder() {}

type GetContactsNotImplementedResponder struct {
	middleware.Responder
}

func (*GetContactsNotImplementedResponder) GetContactsResponder() {}

func GetContactsNotImplemented() GetContactsResponder {
	return &GetContactsNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetContacts has not yet been implemented",
		),
	}
}

type GetContactsResponder interface {
	middleware.Responder
	GetContactsResponder()
}
