// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	model "github.com/powerman/go-service-goswagger-clean-example/internal/api/model"
)

// NewPostContactsParams creates a new PostContactsParams object
// no default values defined in spec.
func NewPostContactsParams() PostContactsParams {

	return PostContactsParams{}
}

// PostContactsParams contains all the bound params for the post contacts operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostContacts
type PostContactsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Contact *model.Contact
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostContactsParams() beforehand.
func (o *PostContactsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body model.Contact
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("contact", "body"))
			} else {
				res = append(res, errors.NewParseError("contact", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Contact = &body
			}
		}
	} else {
		res = append(res, errors.Required("contact", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
