// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"

	model "github.com/powerman/go-service-goswagger-clean-example/internal/api/model"
)

// PostContactsCreatedCode is the HTTP code returned for type PostContactsCreated
const PostContactsCreatedCode int = 201

/*PostContactsCreated Added contact

swagger:response postContactsCreated
*/
type PostContactsCreated struct {

	/*
	  In: Body
	*/
	Payload *model.Contact `json:"body,omitempty"`
}

// NewPostContactsCreated creates PostContactsCreated with default headers values
func NewPostContactsCreated() *PostContactsCreated {

	return &PostContactsCreated{}
}

// WithPayload adds the payload to the post contacts created response
func (o *PostContactsCreated) WithPayload(payload *model.Contact) *PostContactsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contacts created response
func (o *PostContactsCreated) SetPayload(payload *model.Contact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContactsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *PostContactsCreated) PostContactsResponder() {}

/*PostContactsDefault Error

swagger:response postContactsDefault
*/
type PostContactsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewPostContactsDefault creates PostContactsDefault with default headers values
func NewPostContactsDefault(code int) *PostContactsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostContactsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post contacts default response
func (o *PostContactsDefault) WithStatusCode(code int) *PostContactsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post contacts default response
func (o *PostContactsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post contacts default response
func (o *PostContactsDefault) WithPayload(payload *model.Error) *PostContactsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contacts default response
func (o *PostContactsDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContactsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *PostContactsDefault) PostContactsResponder() {}

type PostContactsNotImplementedResponder struct {
	middleware.Responder
}

func (*PostContactsNotImplementedResponder) PostContactsResponder() {}

func PostContactsNotImplemented() PostContactsResponder {
	return &PostContactsNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.PostContacts has not yet been implemented",
		),
	}
}

type PostContactsResponder interface {
	middleware.Responder
	PostContactsResponder()
}
