#!/bin/bash
set -e -o pipefail
export PATH="$PWD/.gobincache:$PATH"
go generate
HADOLINT_VER="2.4.1"
hadolint --version | grep -wq $HADOLINT_VER || curl -sSfL https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VER}/hadolint-"$(uname)"-x86_64 | install -D /dev/stdin .gobincache/hadolint
SHELLCHECK_VER="0.7.2"
shellcheck --version | grep -wq $SHELLCHECK_VER || curl -sSfL https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VER}/shellcheck-v${SHELLCHECK_VER}."$(uname)".x86_64.tar.xz | tar xJf - -C .gobincache --strip-components=1 shellcheck-v${SHELLCHECK_VER}/shellcheck
set -x

hadolint Dockerfile

shellcheck env.sh.dist scripts/*

# When https://github.com/quasilyte/go-ruleguard/issues/78 will be
# implemented and available in golangci-lint then replace using
# build/gorules/rules.go.
mod="$(go list -m)"
(! grep --color=auto -r "\"$mod/internal" pkg)

golangci-lint run

dockerize \
	-wait "tcp://${EXAMPLE_MYSQL_ADDR_HOST}:${EXAMPLE_MYSQL_ADDR_PORT:-3306}" \
	-timeout 30s
gotestsum -- -race -tags=integration "$@" ./...
