// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/powerman/go-service-example/api/openapi/model"
)

// AddContactCreatedCode is the HTTP code returned for type AddContactCreated
const AddContactCreatedCode int = 201

/*AddContactCreated Contact added.

swagger:response addContactCreated
*/
type AddContactCreated struct {

	/*
	  In: Body
	*/
	Payload *model.Contact `json:"body,omitempty"`
}

// NewAddContactCreated creates AddContactCreated with default headers values
func NewAddContactCreated() *AddContactCreated {

	return &AddContactCreated{}
}

// WithPayload adds the payload to the add contact created response
func (o *AddContactCreated) WithPayload(payload *model.Contact) *AddContactCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add contact created response
func (o *AddContactCreated) SetPayload(payload *model.Contact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddContactCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *AddContactCreated) AddContactResponder() {}

/*AddContactDefault - 409.1000: contact already exists


swagger:response addContactDefault
*/
type AddContactDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewAddContactDefault creates AddContactDefault with default headers values
func NewAddContactDefault(code int) *AddContactDefault {
	if code <= 0 {
		code = 500
	}

	return &AddContactDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add contact default response
func (o *AddContactDefault) WithStatusCode(code int) *AddContactDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add contact default response
func (o *AddContactDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add contact default response
func (o *AddContactDefault) WithPayload(payload *model.Error) *AddContactDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add contact default response
func (o *AddContactDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddContactDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *AddContactDefault) AddContactResponder() {}

type AddContactNotImplementedResponder struct {
	middleware.Responder
}

func (*AddContactNotImplementedResponder) AddContactResponder() {}

func AddContactNotImplemented() AddContactResponder {
	return &AddContactNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.AddContact has not yet been implemented",
		),
	}
}

type AddContactResponder interface {
	middleware.Responder
	AddContactResponder()
}
