// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/powerman/go-service-example/internal/app"
)

// AddContactHandlerFunc turns a function with the right signature into a add contact handler
type AddContactHandlerFunc func(AddContactParams, *app.Auth) AddContactResponder

// Handle executing the request and returning a response
func (fn AddContactHandlerFunc) Handle(params AddContactParams, principal *app.Auth) AddContactResponder {
	return fn(params, principal)
}

// AddContactHandler interface for that can handle valid add contact params
type AddContactHandler interface {
	Handle(AddContactParams, *app.Auth) AddContactResponder
}

// NewAddContact creates a new http.Handler for the add contact operation
func NewAddContact(ctx *middleware.Context, handler AddContactHandler) *AddContact {
	return &AddContact{Context: ctx, Handler: handler}
}

/*AddContact swagger:route POST /contacts addContact

Add new contact.

*/
type AddContact struct {
	Context *middleware.Context
	Handler AddContactHandler
}

func (o *AddContact) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddContactParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *app.Auth
	if uprinc != nil {
		principal = uprinc.(*app.Auth) // this is really a app.Auth, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
