// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/powerman/go-service-example/api/openapi/model"
)

// ListContactsOKCode is the HTTP code returned for type ListContactsOK
const ListContactsOKCode int = 200

/*ListContactsOK OK

swagger:response listContactsOK
*/
type ListContactsOK struct {

	/*
	  In: Body
	*/
	Payload []*model.Contact `json:"body,omitempty"`
}

// NewListContactsOK creates ListContactsOK with default headers values
func NewListContactsOK() *ListContactsOK {

	return &ListContactsOK{}
}

// WithPayload adds the payload to the list contacts o k response
func (o *ListContactsOK) WithPayload(payload []*model.Contact) *ListContactsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list contacts o k response
func (o *ListContactsOK) SetPayload(payload []*model.Contact) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListContactsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*model.Contact, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *ListContactsOK) ListContactsResponder() {}

/*ListContactsDefault General errors using same model as used by go-swagger for validation errors.

swagger:response listContactsDefault
*/
type ListContactsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewListContactsDefault creates ListContactsDefault with default headers values
func NewListContactsDefault(code int) *ListContactsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListContactsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list contacts default response
func (o *ListContactsDefault) WithStatusCode(code int) *ListContactsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list contacts default response
func (o *ListContactsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list contacts default response
func (o *ListContactsDefault) WithPayload(payload *model.Error) *ListContactsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list contacts default response
func (o *ListContactsDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListContactsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *ListContactsDefault) ListContactsResponder() {}

type ListContactsNotImplementedResponder struct {
	middleware.Responder
}

func (*ListContactsNotImplementedResponder) ListContactsResponder() {}

func ListContactsNotImplemented() ListContactsResponder {
	return &ListContactsNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.ListContacts has not yet been implemented",
		),
	}
}

type ListContactsResponder interface {
	middleware.Responder
	ListContactsResponder()
}
