// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Address Book
//
//  # ...
//  ## List of all custom errors
//  First number is HTTP Status code, second is value of "code" field in returned JSON object, text description may or may not match "message" field in returned JSON object.
//  - 409.1000: contact already exists
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.2.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
